/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually

  tutorialSidebar: [
    { type: "doc", id: "guides-intro", label: "Introduction" },
    {
      type: "category",
      label: "Getting Started",
      collapsed: false,
      collapsible: true,
      items: [
        {
          type: "category",
          label: "Zero to Hero",
          collapsed: false,
          collapsible: true,
          items: [
            {
              type: "doc",
              id: "getting-started/zero2hero/zero-to-hero",
              label: "Introduction",
            },
            {
              type: "doc",
              id: "getting-started/zero2hero/setup-for-courses-in-gruntwork-academy",
              label: "Setup for the Course",
            },
            {
              type: "doc",
              id: "getting-started/zero2hero/a-web-app-using-docker",
              label: "Create a Web App via Docker",
            },
            {
              type: "doc",
              id: "getting-started/zero2hero/create-an-ecr-repository-with-terraform",
              label: "Create an ECR Repository with Terraform",
            },
            {
              type: "doc",
              id: "getting-started/zero2hero/html-content",
              label: "Foo?",
            },
          ],
        },
        {
          type: "category",
          label: "Setting Up Your Workspace",
          collapsed: false,
          collapsible: true,
          items: [
            {
              type: "doc",
              id: "getting-started/setup-workspace/setup-workspace-intro",
              label: "Introduction",
            },
          ],
        },
        {
          type: "category",
          label: "Common Tasks",
          collapsed: false,
          collapsible: true,
          items: [
            {
              type: "link",
              href: "/foo",
              label: "Guide as TSX",
            },
            {
              type: "doc",
              id: "getting-started/common-tasks/foo",
              label: "Guide as MDX",
            },
          ],
        },
      ],
    },
    // { type: "autogenerated", dirName: "/foo" },
  ],
};

module.exports = sidebars;
