/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  introSidebar: [
    {
      'Overview': [
        'intro/overview/world-class-devops',
        'intro/overview/account-baselines',
        'intro/overview/service-catalog',
        'intro/overview/app-catalog',
        'intro/overview/iac-pipeline',
        'intro/overview/self-service',
        'intro/overview/auto-updates',
      ],
    },
    {
      'Accessing the Dev Portal': [
        'intro/dev-portal/create-account',
        'intro/dev-portal/invite-team',
        'intro/dev-portal/link-github-id',
      ]
    },
    {
      'Setting Up Your Environmant': [
        'intro/environment-setup/stub',
      ]
    },
    {
      'Tool Fundamentals': [
      'intro/tool-fundamentals/stub',
      ]
    },
    {
      'Deploying A Service Module': [
        'intro/first-deployment/stub',
      ]
    },
    {
      type: 'doc',
      id: 'intro/next-steps'
    },
  ],
  guidesSidebar: [
    {
      type: 'doc',
      id: 'guides/welcome'
    },
    {
      'Your Architecture': [
        'guides/your-architecture/stub',
      ],
    },
    {
      'Service Catalog': [
        'guides/service-catalog/stub',
      ]
    },
    {
      'Application Catalog': []
    },
    {
      'Landing Zone': [
        'guides/landing-zone/stub',
      ]
    },
    {
      'Pipelines': [
        'guides/pipelines/stub',
      ]
    },
    {
      'Self Service': []
    },
    {
      'Patcher': [
        'guides/patcher/stub',
      ]
    },
    {
      'Compliance': []
    },
    {
      type: 'doc',
      id: 'guides/support'
    },
  ],
  referenceSidebar: [
    {
      type: 'doc',
      id: 'reference/intro'
    },
    {
      type: 'ref',
      label: 'Service APIs',
      id: 'reference/services/stub'
    },
    {
      type: 'ref',
      label: 'Module APIs',
      id: 'reference/modules/stub'
    },
    {
      type: 'ref',
      label: 'Tools',
      id: 'reference/tools/stub'
    }
  ],
  servicesSidebar: [{type: 'autogenerated', dirName: 'reference/services'}],
  modulesSidebar: [{type: 'autogenerated', dirName: 'reference/modules'}],
  toolsSidebar: [{type: 'autogenerated', dirName: 'reference/tools'}],
};

module.exports = sidebars;
