# This file allows us to define custom environment variables that can be used to override parts of the config. This
# provides a convenient mechanism for specifying different config values in different environments. For example, the
# various databases and caches under the docker-compose folder use this mechanism to inject the corresponding config
# for that database or cache. This also turns out to be a convenient mechanism for defining the schema of all possible
# configuration for this app.
# https://github.com/lorenwest/node-config/wiki/Environment-Variables#custom-environment-variables

algolia:
  appId: DOCS_ALGOLIA_APP_ID
  apiKey: DOCS_ALGOLIA_API_KEY
  indexName: DOCS_ALGOLIA_INDEX_NAME
