# This is the default config for all environments. Check out custom-environment-variables.yml for all possible settings.

algolia:
  appId: 7AWZHGNJE2
  apiKey: 502f05673fef49bd9ccb1b701c727cdd
  indexName: docs_stage
