const sidebar = [
    {
        "label": "What is all this?",
        "type": "category",
        "link": {
            "type": "doc",
            "id": "iac/whats-this/index"
        },
        "items": [
            "iac/whats-this/modules",
            "iac/whats-this/services",
        ]
    },
    {
        "label": "Getting Started",
        "type": "category",
        "link": {
            "type": "doc",
            "id": "iac/getting-started/index"
        },
        "items": [
            "iac/getting-started/setting-up",
            "iac/getting-started/accessing-the-code",
        ]
    },
    {
        "label": "Usage",
        "type": "category",
        "link": {
            "type": "doc",
            "id": "iac/usage/index"
        },
        "items": [
            "iac/usage/using-a-module",
            "iac/usage/using-a-service",
            "iac/usage/composing-your-own-service",
            "iac/usage/customizing-modules",
        ]
    },
    {
        "label": "Library Reference",
        "type": "category",
        "link": {
            "type": "doc",
            "id": "reference/intro"
        },
        "items": [
            {
                type: "category",
                collapsible: true,
                label: "Module Catalog",
                items: [{ type: "autogenerated", dirName: "reference/modules" }],
            },
            {
                type: "category",
                collapsible: true,
                label: "Service Catalog",
                items: [
                  {
                    "App Orchestration": [
                      {
                        type: "autogenerated",
                        dirName: "reference/services/app-orchestration",
                      },
                    ],
                  },
                  {
                    "CI/CD Pipeline": [
                      {
                        type: "autogenerated",
                        dirName: "reference/services/ci-cd-pipeline",
                      },
                    ],
                  },
                  {
                    "Data Storage": [
                      {
                        type: "autogenerated",
                        dirName: "reference/services/data-storage",
                      },
                    ],
                  },
                  {
                    "Landing Zone": [
                      {
                        type: "autogenerated",
                        dirName: "reference/services/landing-zone",
                      },
                    ],
                  },
                  {
                    Networking: [
                      { type: "autogenerated", dirName: "reference/services/networking" },
                    ],
                  },
                  {
                    Security: [
                      { type: "autogenerated", dirName: "reference/services/security" },
                    ],
                  },
                ],
            },
        ]
    }
]

module.exports = sidebar
